[project]
name = "factor-intersection-fallacy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.10.7",
    "numpy>=2.3.4",
    "polars>=1.34.0",
    "scipy>=1.16.2",
]
